import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>Next.js</h1>
        </header>
        <main>{children}</main>
        <footer>
          <p>
            <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              Powered by{" "}
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
